### ISSUE TITLE
自动赠送荧光棒bug

### ISSUE THREAD

**Issue by D3ee** [starudream/douyu-task#26]
room和remaining填写一样不赠送，room 9999 remaining改成自己养牌子的直播间 不赠送， room改成自己养牌子的直播间，remaining改成9999就赠送成功了
![image](https://github.com/starudream/douyu-task/assets/37684328/6fd18318-8f4f-416a-b6ac-314fee79999b)

**Comment by starudream** [comment]
新版本这部分重写了。
之前送礼物的逻辑是所有牌子送 `1` 个，其余的荧光棒送给 `remaining`，`room` 参数只用于每日进直播间领荧光棒用，和送荧光棒无关。

```yaml
# 基本配置
douyu:
  # 荧光棒分配
  assigns:
    # { room, count, all }
    # room 直播间号，如果是 0 的话，对已有牌子的直播间分别送上 count 数量的荧光棒
    # count 荧光棒数量
    # all 是否全部分配，建议最后一个直播间设置为 all: true，这样就可以把剩余的荧光棒全部分配出去
    - count: 1
    - room: 99999
      count: 10
    - room: 9999
      all: true
```

上面的配置所有牌子的直播间会送 `1` 根荧光棒，`99999` 会送 `11` 根，剩下的全送给 `9999`
