### ISSUE TITLE
有没有考虑根据荧光棒的结束时间考虑赠送不赠送？

### ISSUE THREAD

**Issue by D3ee** [starudream/douyu-task#27]
比如如果荧光棒有效期大于1天，则周六周日送，如果小于1天则当天送？因为周末可能会开双倍。谢谢大佬~

**Comment by D3ee** [comment]
而且根据规则七天不送礼物才会掉亲密度，大佬可以考虑加上，麻烦的话不加也行~

**Comment by starudream** [comment]
v2.0.2 版本已更新，送礼物默认检测荧光棒是否今天过期。

配置文件可以这样写：

```yaml
# 计划任务
cron:
  # 刷新背包荧光棒，每天 00:10:00 获取一次
  refresh: "0 10 0 * * *"
  # 送免费的荧光棒续牌子，每天 23:50:00 执行一次，如果有荧光棒当天过期则按照配置的顺序送出
  renewal: "0 50 23 * * *"
```

> 可能有问题的就是超粉团周日过期如果计划任务配置的周日不执行，那就不会送了，但是应该不会有人配置周末不执行吧。
