### ISSUE TITLE
大佬，能否加入Bark通知推送？

### ISSUE THREAD

**Issue by tracy1949** [starudream/douyu-task#30]

**Comment by starudream** [comment]
- https://github.com/starudream/douyu-task/releases/tag/v3.0.0

```yaml
ntfy:
  webhook:
    url: http://127.0.0.1:8080/push
    method: POST
    type: JSON
    key: body
    extra:
      title: ntfy
      category: xxx
      device_key: xxx
    headers:
      Content-Type: "application/json; charset=utf-8"
```

- https://github.com/Finb/bark-server/blob/master/docs/API_V2.md#curl
- https://pkg.go.dev/github.com/starudream/go-lib/ntfy/v2#WebhookConfig
